import Head from 'next/head';
import Navbar from '../components/Navbar';
import { Heading1, SubHeading1, Paragraph } from '../components/Typography';
import styles from '../styles/Home.module.scss';

const HeaderText = () => {
	return (
		<header className={styles.HeaderWrapper}>
			<div className={styles.HeaderText}>
				<SubHeading1 text='So, you want to travel to' />
				<Heading1 text='SPACE' />
				<Paragraph
					text='Let’s face it; if you want to go to space, you might as well
					genuinely go to outer space and not hover kind of on the
					edge of it. Well sit back, and relax because we’ll give you
					a truly out of this world experience!'
				/>
			</div>
			<div className={styles.ButtonWrapper}>
				<button className={styles.exploreButton}>EXPLORE</button>
			</div>
		</header>
	);
};

export default function Home() {
	return (
		<div className={styles.background}>
			<Head>
				<title>Space Travel Agency</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar current='home' />
			<HeaderText />
		</div>
	);
}
